### ISSUE TITLE
Segfault in x64asm::Linker::link

### ISSUE THREAD

**Issue by tterribe** [StanfordPL/stoke-release#22] opened 2015-05-27 22:59 UTC
#0  0x00000000006c668d in x64asm::Linker::link(x64asm::Function&) ()
#1  0x000000000046a71c in stoke::Sandbox::compile(stoke::Cfg const&) ()
#2  0x0000000000456334 in stoke::CostFunction::set_target(stoke::Cfg const&, bool, bool) ()
#3  0x0000000000430faa in stoke::CostFunction::CostFunction(stoke::Sandbox*) ()
#4  0x000000000040bf75 in main ()

https://people.xiph.org/~tterribe/daala/check_partition2.tar.gz contains source code, binary, extracted .s files, testcases, and config files.

gdb --args ./stoke_search --config search.conf

to reproduce.

**Comment by tterribe** [comment] 2015-05-27 23:03
Better backtrace (with make debug):

#0  0x00000000007127fd in x64asm::Linker::link(x64asm::Function&) ()
#1  0x0000000000497162 in stoke::Sandbox::compile (this=0x7fffffffc200, 
    cfg=...) at src/sandbox/sandbox.cc:101
#2  0x000000000048aa41 in stoke::Sandbox::run (this=0x7fffffffc200, cfg=...)
    at ././src/sandbox/sandbox.h:114
#3  0x000000000048768b in stoke::CostFunction::set_target (
    this=0x7fffffffb150, target=..., stack_out=false, heap_out=false)
    at src/cost/cost_function.cc:49
#4  0x000000000041c409 in stoke::CostFunction::CostFunction (
    this=0x7fffffffb150, sb=0x7fffffffc200) at ././src/cost/cost_function.h:56
#5  0x000000000041c830 in stoke::CostFunctionGadget::CostFunctionGadget (
    this=0x7fffffffb150, target=..., sb=0x7fffffffc200)
    at ././tools/gadgets/cost_function.h:30
#6  0x0000000000411500 in main (argc=3, argv=0x7fffffffd928)
    at tools/apps/stoke_search.cc:198

**Comment by bchurchill** [comment] 2015-05-28 06:33
I haven't looked closely or fully reproduced this yet, but I ran your
files with a more recent version of stoke and it reported that %esi
isn't in the def-in set, but it should be.  Could you try adding %esi to
the list and seeing if it works?  Either way it's a bug, but if that's
the cause it will help us track things down.

Berkeley

**Comment by bchurchill** [comment] 2015-05-28 06:44
Yeah, I don't seem to be able to reproduce this at all.  If fixing
def_ins doesn't help, could you let us know what disto you're on, and
the output of these commands:

cat /proc/cpuinfo | grep flags | head -n1
gcc -v

If you think something in your local copy has gotten messed up, 'make
dist_clean' should help.  Also, you can run 'make test' and everything
should pass.  If not, something is wrong.

**Comment by tterribe** [comment] 2015-05-29 21:15
I added %esi to the list, but still get the same crash. Distro is Gentoo (which, I should point out, cannot run the binaries until I copy libz3.so somewhere into LD_LIBRARY_PATH).

cat /proc/cpuinfo | grep flags | head -n1
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm

gcc -v
Using built-in specs.
COLLECT_GCC=/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.1/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/4.9.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /var/tmp/portage/sys-devel/gcc-4.9.1/work/gcc-4.9.1/configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.1 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.1/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/4.9.1 --mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/4.9.1/man --infodir=/usr/share/gcc-data/x86_64-pc-linux-gnu/4.9.1/info --with-gxx-include-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.1/include/g++-v4 --with-python-dir=/share/gcc-data/x86_64-pc-linux-gnu/4.9.1/python --enable-languages=c,c++,java,fortran --enable-obsolete --enable-secureplt --disable-werror --with-system-zlib --enable-nls --without-included-gettext --enable-checking=release --with-bugurl=https://bugs.gentoo.org/ --with-pkgversion='Gentoo 4.9.1 p1.0, pie-0.6.0' --enable-libstdcxx-time --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --enable-multilib --with-multilib-list=m32,m64 --disable-altivec --disable-fixed-point --enable-targets=all --enable-libgomp --disable-libmudflap --disable-libssp --enable-lto --with-cloog --disable-isl-version-check
Thread model: posix
gcc version 4.9.1 (Gentoo 4.9.1 p1.0, pie-0.6.0)

Where is the "more recent version"?

**Comment by bchurchill** [comment] 2015-05-30 13:49
The libz3 issue is expected.  I think the 'stoke' script in bin/ adjusts
the LD_LIBRARY_PATH before running the binaries, so you can use that for
convenience if you like.

Our ability to help you may be limited since gentoo isn't a supported
platform and we can't reproduce it, but we'll make an effort.  Could you
verify this happens with a fresh code checkout using the haswell build? 
What happens if you run 'make test'?  Will the tutorial in
examples/tutorial work?  I'm trying to get a sense of if the code is
always failing there, or if it's only sometimes.  Also, if you build
x64asm with 'make debug' (by going into the src/ext/x64asm directory,
running "make clean && make debug", and then rebuilding stoke itself)
that might give more information on what's going wrong in link().

The newer version isn't stable -- it's just where we have our research
code and it's not public.  Yet, I don't think it would help you, because
I wasn't able to reproduce the problem with the release, and I would be
surprised if we somehow fixed this.

**Comment by tterribe** [comment] 2015-06-01 21:25
> I think the 'stoke' script in bin/ adjusts the LD_LIBRARY_PATH before running

This was not working for whatever reason. I had to _stop_ using that script to get a useful error message (otherwise bash simply reported failing to load the .so as a segafult in a child process) before I could even figure out what the problem was. But that's a separate issue.

I am not certain what 'the Haswell build' refers to. I checked out 232ca096de53be8f1f528b22f3b610566f386cae (tip as of the time of checkout).

make test produces

[----------] 1 test from ValidatorFuzzTest
[ RUN      ] ValidatorFuzzTest.RandomInstructionRandomState
[----------] * Seed 489273
[----------] * vpcmpistri $0xfe, 0x16(%r8), %xmm2
[----------]   - No validator support
[----------] * minss 0x64(%rsp,%rdx,8), %xmm5  
[----------]   - No validator support
[----------] * movntdqa 0x16(%r8), %xmm14
[----------]   - No validator support
[----------] * paddsb %xmm3, %xmm12
[----------]   - No validator support
[----------] * cvtpi2pd 0x64(%rsp,%rdx,8), %xmm3
[----------] * movupd 0x64(%rdx), %xmm1
[----------] * btl $0x40, %esi
[----------]   - No validator support
[----------] * phaddw %xmm0, %xmm0
[----------] * setp %dl
[----------] * vandnpd %xmm15, %xmm12, %xmm7   
[----------] * testq %r13, %rsp
[----------] * andl 0x16(%r8), %esp
[----------] * vpmulhuw -0x16(%r8), %ymm9, %ymm11
[----------]   - No validator support
[----------] * vpmaxub -0x16(%r8), %xmm15, %xmm4
[----------] * vdpps $0xde, %ymm5, %ymm8, %ymm5
[----------]   - No validator support
[----------] * vcvtsi2sdq 0x64(%rdx), %xmm1, %xmm6
[----------]   - No validator support
[----------] * vpblendd $0x7f, %ymm3, %ymm2, %ymm12
[----------]   - No validator support
[----------] * vpermilps %xmm0, %xmm1, %xmm6   
[----------]   - No validator support
[----------] * imulw -0x64(%rsp,%rdx,8)
[----------]   - No validator support
[----------] * vdivpd 0x16(%r8), %xmm1, %xmm6  
[----------]   - Could not generate state: Memory dereference misaligned.
[----------] * xaddb %al, %r13b
[----------] * setno %sil
[----------] * testb %cl, %cl
[----------] * vpextrb $0xfe, %xmm7, %rax
[----------]   - No validator support
[----------] * sarb %cl, %r12b
[----------] * vmovaps -0x64(%rsp,%rdx,8), %xmm2
[----------]   - Could not generate state: Memory dereference misaligned.
[----------] * addb (%rax), %r8b
[----------] * vphsubd %xmm14, %xmm0, %xmm1
[----------] * vroundps $0xff, 0x64(%rdx), %ymm6
[----------]   - No validator support
[----------] * vpsrlw -0x64(%rax,%rcx,4), %ymm10, %ymm7
[----------]   - No validator support
[----------] * vmaskmovpd -0x16(%r8), %ymm15, %ymm11
[----------]   - No validator support
[----------] * salw %cl, %si
[----------] * vpminuw 0x16(%r8), %ymm6, %ymm9 
[----------]   - Could not generate state: Memory dereference misaligned.
[----------] * pmovzxwq 0x64(%rdx), %xmm10
[----------] * cmpw $0x3, 0x64(%rdx)
[----------] * vpshufd $0xfe, %ymm3, %ymm14
[----------]   - No validator support
[----------] * cmpxchgb %dl, %r13b
[----------]   - No validator support
[----------] * salw $0x1, %cx
[----------] * vmulpd 0x64(%rsp,%rdx,8), %xmm15, %xmm11
[----------]   - Could not generate state: Memory dereference misaligned.
[----------] * phaddw -0x64(%rax,%rcx,4), %mm0 
[----------]   - No validator support
[----------] * vpackssdw %xmm14, %xmm2, %xmm14 
[----------]   - No validator support
[----------] * vpsubsw %ymm10, %ymm0, %ymm15   
[----------] * sbbb $0x8, %al
[----------] * movzwq (%rax), %rsp
[----------] * vpaddd %ymm14, %ymm14, %ymm13   
[----------] * vmaxss %xmm15, %xmm11, %xmm12   
[----------]   - No validator support
[----------] * vpermq $0xff, %ymm15, %ymm6
[----------]   - No validator support
[----------] * movswq %cx, %r12
[----------] * vsubsd %xmm0, %xmm12, %xmm14
[----------] * testq $0x7fff, %rax
[----------] * rorw $0x1, %r11w
[----------] * pabsw -0x16(%r8), %xmm15
[----------]   - Could not generate state: Memory dereference misaligned.
[----------] * vpsubb 0x64(%rsp,%rdx,8), %ymm6, %ymm11
[----------]   - Could not generate state: Memory dereference misaligned.
[----------] * vmovsldup %xmm14, %xmm1
[----------]   - No validator support
[----------] * idivw %r11w
[----------]   - No validator support
[----------] * vpmaxud 0x64(%rax,%rcx,4), %xmm12, %xmm9
[----------] * minpd 0x64(%rax,%rcx,4), %xmm10 
[----------] * vpaddw %xmm1, %xmm10, %xmm11
[----------] * phaddd %xmm8, %xmm1
[----------] * sarq $0x1, %rax
[----------] * shrl %cl, %ebp
[----------] * vtestps %xmm6, %xmm10
[----------]   - No validator support
[----------] * andw 0x64(%rdx), %r8w
[----------] * vcvtdq2pd %ymm4, %ymm14
[----------] * pavgb 0x64(%rsp,%rdx,8), %mm1   
[----------]   - No validator support
[----------] * vsqrtss -0x64(%rsp,%rdx,8), %xmm13, %xmm14
[----------] * pmovzxwq %xmm2, %xmm2
[----------] * cvtss2siq -0x16(%r8), %rcx
[----------]   - No validator support
[----------] * pinsrw $0xe0, %r13d, %xmm5
[----------]   - No validator support
[----------] * roundpd $0xff, %xmm6, %xmm7
[----------]   - No validator support
[----------] * sbbl $0xfffffffa, %eax
[----------] * vpabsw %ymm15, %ymm7
[----------] * vpmaddwd %xmm11, %xmm10, %xmm7  
[----------]   - No validator support
[----------] * imulb %r9b
[----------]   - No validator support
[----------] * xorb %bl, %r13b
[----------] * movzbl %r11b, %edx
[----------] * setng %spl
[----------] * vpinsrd $0xff, %r12d, %xmm0, %xmm12
[----------]   - No validator support
[----------] * shrw $0x1, %si
[----------] * cvttps2dq %xmm10, %xmm9
[----------] * orb (%rax), %r14b
[----------] * pextrw $0xe0, %xmm2, %r13d
[----------]   - No validator support
[----------] * incq %r15
[----------] * vcvttpd2dq -0x16(%r8), %xmm2
[----------]   - No validator support
[----------] * testl $0xffffffff, %ecx
[----------] * sets %dl
[----------] * sbbb %r14b, %bpl
[----------] * vsqrtps -0x64(%rsp,%rdx,8), %xmm11
[----------]   - Could not generate state: Memory dereference misaligned.
[----------] * insertps $0xfc, %xmm11, %xmm12  
[----------]   - No validator support
[----------] * vphsubsw %ymm1, %ymm2, %ymm3
[----------]   - No validator support
[----------] * vmpsadbw $0x0, -0x64(%rsp,%rdx,8), %ymm13, %ymm6
[----------]   - No validator support
[----------] * blendps $0xff, -0x16(%r8), %xmm8
[----------]   - No validator support
[----------] * andpd %xmm10, %xmm14
[----------] * shrl %cl, %esp
[----------] * vpshufb 0x64(%rdx), %ymm13, %ymm13
[----------]   - No validator support
[----------] * verr %r11w
[----------]   - No validator support
[----------] * andw %r9w, %r12w
[----------] * vrcpss 0x64(%rdx), %xmm4, %xmm4 
[----------] * vpshufb %ymm7, %ymm14, %ymm0
[----------]   - No validator support
[----------] * vcmpss $0xfa, %xmm14, %xmm15, %xmm2
[----------]   - No validator support
././tests/validator/fuzz.h:200: Failure
Expected: (success) >= (min_success), actual: 0 vs 25
[  FAILED  ] ValidatorFuzzTest.RandomInstructionRandomState (1717 ms)

...

[  FAILED  ] 1 test, listed below:
[  FAILED  ] ValidatorFuzzTest.RandomInstructionRandomState

Rebuilding x64asm with make debug, and now things appear to work (both the tutorial and my code). I don't think I changed anything else, but making clean in x64asm and the top level and rebuilding without make debug, and things still work.

Not sure what to do here, as now both of us cannot reproduce. If you wish to assume pilot error somewhere on my part and close this, that's fine.

**Comment by bchurchill** [comment] 2015-06-01 21:30
Thank you for taking the time to look into it.  It's not uncommon for
something to get messed up in the build system.  The haswell build is
the default one; if you type "make" you get a haswell build.

The error you get from 'make test' is odd, but it's probably okay for
what you're doing. 

If everything is working fine, then let's go ahead and close this, but
feel free to reopen if needed.

**Closed** 2015-06-01 21:39 UTC
